import {expect,it} from 'vitest';
import {PerformanceEngine} from '../../src/performance/engine';
import {defaultVariations,type Variations} from '../../src/performance-settings/model';
import type {Input} from '../../src/performance/model';
function rig(variation:Partial<Variations>={}){const e=new PerformanceEngine(48000,{chord:[0],mode:[0,1,2,3,4,5,6,7,8,9,10,11],holdNumber:2,variations:{...defaultVariations(),...variation}});let t=0;return{e,send:(input:Input)=>{e.enqueue(input,t);return e.advance(t,++t).flatMap(f=>f.actions);},pitches:()=>e.snapshot.sounding.map(n=>n.pitch).sort((a,b)=>a-b)};}
it('independent MIDI adds and releases each trigger without reattacking unrelated notes',()=>{const r=rig({multiMidi:true});r.send({type:'midiOn',id:'a',pitch:60,velocity:80});expect(r.send({type:'midiOn',id:'b',pitch:64,velocity:90}).map(a=>[a.type,a.pitch])).toEqual([['on',64]]);expect(r.pitches()).toEqual([60,64]);expect(r.send({type:'midiOff',id:'b'}).map(a=>[a.type,a.pitch])).toEqual([['off',64]]);expect(r.pitches()).toEqual([60]);});
it('independent MIDI preserves overlapping chord ownership',()=>{const r=rig({multiMidi:true});r.send({type:'settings',settings:{chord:[0,4]}});r.send({type:'midiOn',id:'a',pitch:60,velocity:80});r.send({type:'midiOn',id:'b',pitch:64,velocity:90});expect(r.send({type:'midiOff',id:'a'}).map(a=>[a.type,a.pitch])).toEqual([['off',60]]);expect(r.pitches()).toEqual([64,68]);});
it('unlimited Sustain retains more than Hold Number',()=>{const r=rig({sustainLimit:false});r.send({type:'control',control:'sustain',active:true});for(const pitch of [60,62,64])r.send({type:'pointer',pitch,down:true});r.send({type:'release'});expect(r.pitches()).toEqual([60,62,64]);});
it('refreshing Sustain age changes which individual pitch is evicted',()=>{const r=rig({refreshSustainAge:true});r.send({type:'control',control:'sustain',active:true});for(const pitch of [60,62,60,64])r.send({type:'pointer',pitch,down:true});expect(r.pitches()).toEqual([60,64]);});
it('optional Sustain reattack strikes a retained pitch again',()=>{const r=rig({sustainRetrigger:true});r.send({type:'control',control:'sustain',active:true});r.send({type:'pointer',pitch:60,down:true});expect(r.send({type:'pointer',pitch:60,strike:true}).map(a=>a.type)).toEqual(['off','on']);});
it('optional scale clearing releases retained pitches filtered by the new mode',()=>{const r=rig({retainAcrossScale:false});r.send({type:'control',control:'sustain',active:true});r.send({type:'pointer',pitch:61,down:true});r.send({type:'release'});r.send({type:'settings',settings:{mode:[0]}});expect(r.pitches()).toEqual([]);});
it('short input ignore suppresses mouse and MIDI taps wholly between ticks',()=>{const e=new PerformanceEngine(48000,{metronome:true,tempo:120,variations:{...defaultVariations(),shortInput:'ignore'}});e.enqueue({type:'pointer',pitch:60,down:true},1);e.enqueue({type:'release'},2);e.enqueue({type:'midiOn',id:'a',pitch:60,velocity:80},3);e.enqueue({type:'midiOff',id:'a'},4);expect(e.advance(0,48001).flatMap(f=>f.actions)).toEqual([]);});
for(const policy of ['off','current','all'] as const)it(`Drone Repeat policy ${policy}`,()=>{const r=rig({repeatDrone:policy});r.send({type:'pointer',pitch:60,down:true});r.send({type:'control',control:'drone',active:true});r.send({type:'pointer',pitch:64});r.send({type:'control',control:'repeat',active:true});const attacks=r.e.advance(4,12001).flatMap(f=>f.actions).filter(a=>a.type==='on').map(a=>a.pitch).sort();expect(attacks).toEqual(policy==='all'?[60,64]:[64]);});
