/*! Copyright (c) 2026 Ethan Joffe */
import originalIcon from '../website/original-icon.png';
import {sounds} from './audio/sounds';
import {chords,modes} from './fixtures/instruments';
export function mount():void {
 document.querySelector('#instrument')!.innerHTML=`
 <header class="app-header"><a class="brand" href="/" aria-label="Harmony Grid homepage"><img src="${originalIcon}" alt="" width="25" height="31">harmony grid</a><div class="app-menu"><button id="make-chord">Make chord <kbd>N</kbd></button><button id="make-mode">Make mode <kbd>M</kbd></button></div><span id="capture-notice" role="status" hidden></span><div class="header-right"><span class="document-title">Synthetic fixtures</span><button id="performance-settings-button">Performance & MIDI…</button><button id="edit-slots">Edit…</button><button id="file-menu">File…</button><button id="help" title="Playing guide and examples · F1">Help</button></div></header>
 <div class="workspace"><aside class="sidebar">
 <section><div class="eyebrow">Scale root</div><div class="scale-heading"><div><span class="tonic" id="root">C</span><span class="scale-name" id="mode-name">Major</span></div><button id="set-root" title="Set scale root at the lead pitch"><kbd>Tab</kbd></button></div><div class="scale-sub"><span>Set root at pointer</span><span>♭</span></div></section>
 <section><div class="section-head"><span class="eyebrow">Modes</span><span class="hint" id="selection-target">Shift / Caps + 0–9</span></div><div class="modes">${modes.map((m,i)=>`<button class="mode ${i===1?'active':''}" data-mode="${i}"><span class="radio"></span>${m.name}<span class="slot">${(i+1)%10}</span></button>`).join('')}</div></section>
 <section class="separator"><div class="section-head"><span class="eyebrow">Performance</span><span class="hint">⌘ to latch*</span></div><div class="performance">${[['sustain','Space'],['hold','G'],['drone','Y'],['repeat','D']].map(([c,k])=>`<button class="control" data-control="${c}" aria-pressed="false">${c[0].toUpperCase()+c.slice(1)}<kbd>${k}</kbd></button>`).join('')}</div><div class="control-note">F toggles Sustain · Y toggles Drone<br>* Hold and Repeat: ⌘ + key</div></section>
 <section class="metronome"><div class="section-head"><span class="metronome-heading"><svg class="metronome-icon" viewBox="0 0 48 48" width="42" height="42" aria-hidden="true" focusable="false"><g stroke="currentColor" stroke-linejoin="round"><path d="M21 7H29L41 41H9Z" fill="none" stroke-width="2.8"/><path d="M21 7 9 41 3 39 17 7Z" fill="none" stroke-width="2.7"/><path d="M17 7Q18 3 21 3H28Q30 3 31 7L32 10H28L27 8H22L21 10H16Z" fill="currentColor" stroke="none"/><path d="M2 37 9 39H41L42 46H9L3 43Z" fill="currentColor" stroke="none"/><path d="M25 10v28m-3-23h6m-6 6h6m-6 6h6m-6 6h6" fill="none" stroke-width="1.8"/><path d="M25 40 42 12" fill="none" stroke-width="2.3" stroke-linecap="round"/><path d="m40 9 3 2-2 5-3-2Z" fill="currentColor" stroke-width="1.5"/></g></svg><span class="eyebrow">Metronome</span></span><button id="metronome" aria-pressed="false"><kbd>T</kbd></button></div><div class="tempo-readout"><span class="rate" id="tempo">240</span><span class="units">ticks<br>/ min</span><span class="metro-state"><span id="metro-state">OFF</span><span class="pulses"><i class="pulse"></i><i class="pulse"></i></span></span></div><div class="tempo-keys">${[['½','q'],['2×','w'],['⅔','e'],['³⁄₂','r']].map(([v,k])=>`<button class="tempo-key" data-tempo="${k}" title="Hold for temporary change; Command-click for permanent"><span>${v}</span><kbd>${k.toUpperCase()}</kbd></button>`).join('')}</div><div class="tempo-bottom"><span><button id="slower"><kbd>A</kbd> −1</button> <button id="faster"><kbd>S</kbd> +1</button></span><span>⌘ to latch</span></div></section>
 </aside><section class="playing-area"><div class="chord-head"><span class="eyebrow">Chords</span><span>0–9 select chord · Shift / Caps selects mode</span></div><div class="chords">${chords.map((c,i)=>`<button class="chord ${i===1?'active':''}" data-chord="${i}"><span class="slot">${(i+1)%10}</span>${c.name}</button>`).join('')}</div>
 <div class="grid-head"><div class="left"><strong>Harmony grid</strong><button id="axes" title="Edit grid intervals and playing range">→ 4 ↑ 3 · Grid & register…</button><div class="midi-controls">${[['playChords','Play Chords'],['mouseSolo','Mouse Solo'],['thru','Thru'],['setsRoot','Sets Root']].map(([id,label])=>`<button id="${id}" aria-pressed="${id==='playChords'}">${label}</button>`).join('')}</div></div><button id="auto" aria-pressed="false">○ Auto Button</button></div>
 <div class="grid-frame"><canvas id="grid" aria-label="Harmony grid: drag to play the selected chord" tabindex="0"></canvas></div>
 <div class="clavier-head"><div class="left"><span class="eyebrow">Clavier</span><span id="clavier-range">C3 – C6</span></div><div class="right"><button id="smooth" aria-pressed="false">Smooth Clavier ○</button><button id="show-clavier" aria-pressed="true">Show ●</button></div></div><div class="clavier"><canvas id="clavier" aria-label="Clavier: C3 through C6" tabindex="0"></canvas></div>
 <div class="legend"><span class="legend-item capture-legend"><i class="legend-mark selected"></i>Selected</span><span class="legend-item"><i class="legend-mark"></i>Scale</span><span class="legend-item"><i class="legend-mark root"></i>Root</span><span class="legend-item"><i class="legend-mark sounding"></i>Sounding</span><span class="legend-item"><i class="legend-mark filtered"></i>Filtered</span><span class="legend-item"><i class="legend-mark midi"></i>MIDI pitch</span><span class="legend-item"><i class="legend-mark pitchclass"></i>Pitch class</span><span class="lead" id="lead">Lead C4</span></div>
 </section></div>`;
 document.querySelector('#review-bar')!.innerHTML=`<button id="start" class="start">Start sound</button><button id="panic">All Notes Off · Esc</button><select id="sound" aria-label="Internal sound">${Object.entries(sounds).map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select><button id="retry-palette" hidden title="Release notes and restart sound to retry loading the palette">Retry palette</button><button id="connect-midi">Connect MIDI</button><select id="midi-input" aria-label="MIDI input"><option value="">MIDI input</option></select><select id="midi-output" aria-label="MIDI output"><option value="">MIDI output</option></select><button id="export">Export trace</button><small id="status" role="status">Start sound to play</small>`;
}
